### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by ouceduxzk** [kohillyang/mx-openpose#2]
After following your instruction and I start to run the demo, there is one error occurred, 
RuntimeError: stage2_unit4_conv3_weight is not presented

How should i fix this problem?
Thanks

**Comment by yaochx** [comment]
great works, thanks!
same as above.

**Comment by kohillyang** [comment]
I changed the symbol file but i didn't upgrade model file, here you can find the new model.
https://pan.baidu.com/s/1qYgaHoo
the password is e37a
