### ISSUE TITLE
C++ implementation

### ISSUE THREAD

**Issue by BenLag2906** [kohillyang/mx-openpose#5]
Hi, 
I try to use your implementation and your result in c++.

MxPredCreate seem ok in c++, but the MXPredSetInput crashed. But other model like ssd is OK with the same code.

Do you have an idea to see your results ?
Regards.

Benoit

**Comment by kohillyang** [comment]
There are many reasons. I think you'd better check the size of the input buffer to ignore indexes out of bounds.

**Comment by BenLag2906** [comment]
Hi,

Normally if i compare with python code, my input in c++ and yours, in python are the same :
 368*368*3 * batch.
If you have another idea.
your model seem to be exported correctly.

**Comment by BenLag2906** [comment]
Hi,
I don't understand why i can't export your model in c++ to test it...
Do you know a special manipulation to export/deploy your model, or if you have a trained model which can be use in c++, you can contact me by mail : lagadecben@gmail.com

Best regards

**Comment by BenLag2906** [comment]
any idea ?
