### ISSUE TITLE
Train dataset

### ISSUE THREAD

**Issue by MBocchi** [kohillyang/mx-openpose#6]
Hi,
I have implemented the yks_pose model and it works fine! I would like to know which dataset has been used to obtain the yks_pose model (8600 epochs). Can you give me the name or a link of this dataset?
Thank you

**Comment by kohillyang** [comment]
Its name is mpi.

You can download it from <http://human-pose.mpi-inf.mpg.de/>.

**Comment by MBocchi** [comment]
Thank you kohillyang!
